spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/example?characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true

  freemarker:
    template-loader-path: classpath:/templates
  mvc:
    static-path-pattern: /static/**



# 这个是为了解决 Invalid bound statement (not found): com.yuqi.jpalearning.mapper.SysUserMapper.getAll




#mybatis:
#  mapper-locations: classpath*:mapper/*
#  config-location: classpath:mybatis-config.xml
#  type-aliases-package: com.yuqi.jpalearning.model


mybatis-plus:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.yuqi.jpalearning.model

